services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    environment:
      AWS_REGION: ${CLUSTER_REGION}
    ports:
      - "8888:8888"
      - "8080:8080"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
